# Generated by Django 5.1.7 on 2025-05-07 07:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ban",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("TenBan", models.CharField(max_length=50)),
                ("SoChoNgoi", models.IntegerField()),
                ("ViTri", models.CharField(max_length=50)),
                ("TrangThai", models.CharField(default="Trống", max_length=20)),
            ],
            options={
                "db_table": "Ban",
            },
        ),
        migrations.CreateModel(
            name="DatBan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Ngay", models.DateField()),
                ("Gio", models.TimeField()),
                ("SoNguoi", models.IntegerField()),
                ("TrangThai", models.CharField(default="Đang chờ", max_length=20)),
                (
                    "IDBan",
                    models.ForeignKey(
                        db_column="IDBan",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurant.ban",
                    ),
                ),
            ],
            options={
                "db_table": "DatBan",
            },
        ),
        migrations.CreateModel(
            name="LoaiMonAn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("TenLoai", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "LoaiMonAn",
            },
        ),
        migrations.CreateModel(
            name="NguoiDung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("HoTen", models.CharField(max_length=100)),
                ("Email", models.EmailField(max_length=254, unique=True)),
                ("SDT", models.CharField(max_length=20)),
                ("MatKhau", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "NguoiDung",
            },
        ),
        migrations.CreateModel(
            name="VaiTro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("TenVaiTro", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "VaiTro",
            },
        ),
        migrations.CreateModel(
            name="DonHang",
            fields=[
                (
                    "IDDatBan",
                    models.OneToOneField(
                        db_column="IDDatBan",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="restaurant.datban",
                    ),
                ),
                (
                    "TongTien",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("TrangThai", models.CharField(default="Đang xử lý", max_length=20)),
            ],
            options={
                "db_table": "DonHang",
            },
        ),
        migrations.CreateModel(
            name="MonAn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("TenMon", models.CharField(max_length=100)),
                ("Gia", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "IDLoai",
                    models.ForeignKey(
                        db_column="IDLoai",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="restaurant.loaimonan",
                    ),
                ),
            ],
            options={
                "db_table": "MonAn",
            },
        ),
        migrations.AddField(
            model_name="datban",
            name="IDNguoiDung",
            field=models.ForeignKey(
                db_column="IDNguoiDung",
                on_delete=django.db.models.deletion.CASCADE,
                to="restaurant.nguoidung",
            ),
        ),
        migrations.AddField(
            model_name="nguoidung",
            name="IDVaiTro",
            field=models.ForeignKey(
                db_column="IDVaiTro",
                on_delete=django.db.models.deletion.CASCADE,
                to="restaurant.vaitro",
            ),
        ),
        migrations.CreateModel(
            name="ThanhToan",
            fields=[
                (
                    "IDDonHang",
                    models.OneToOneField(
                        db_column="IDDonHang",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="restaurant.donhang",
                    ),
                ),
                ("SoTien", models.DecimalField(decimal_places=2, max_digits=10)),
                ("PhuongThuc", models.CharField(max_length=20)),
                ("TrangThai", models.CharField(default="Thành công", max_length=20)),
            ],
            options={
                "db_table": "ThanhToan",
            },
        ),
        migrations.CreateModel(
            name="ChiTietDon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("SoLuong", models.IntegerField()),
                ("Gia", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "IDMonAn",
                    models.ForeignKey(
                        db_column="IDMonAn",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurant.monan",
                    ),
                ),
                (
                    "IDDonHang",
                    models.ForeignKey(
                        db_column="IDDonHang",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurant.donhang",
                    ),
                ),
            ],
            options={
                "db_table": "ChiTietDon",
            },
        ),
        migrations.CreateModel(
            name="DanhGia",
            fields=[
                (
                    "IDThanhToan",
                    models.OneToOneField(
                        db_column="IDThanhToan",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="restaurant.thanhtoan",
                    ),
                ),
                (
                    "Diem",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("NoiDung", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "DanhGia",
            },
        ),
    ]
