# Generated by Django 5.1.7 on 2025-05-07 09:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ban",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="chitietdon",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="danhgia",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="datban",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="donhang",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="loaimonan",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="monan",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="nguoidung",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="thanhtoan",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="vaitro",
            options={"managed": False},
        ),
    ]
