# Generated by Django 5.1.7 on 2025-05-09 20:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0002_alter_ban_options_alter_chitietdon_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nguoidung",
            options={},
        ),
    ]
