version: "3.9"

services:
  backend:
    build:
      context: ./backend_app
      dockerfile: Dockerfile
    env_file:
      - ./backend_app/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend_app:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build:
      context: ./frontend_app
      dockerfile: Dockerfile
    env_file:
      - ./frontend_app/.env.development
    ports:
      - "5173:5173"
    volumes:
      - ./frontend_app:/app
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 5